## Tutorial 16: Linear Algebra

This is a very brief introduction to matrix linear algebra using
numpy.

### Vectors and dot products

A one dimensional numpy array can be thought of a mathematical vector.
That is, the array is some element in an n-dimensional space:

$$a \in \mathbb{R}^n$$.

For example, if n is 2 this is just a point on the plane. If n is three,
it's a point in 3-dimensional space. A vector has a direction and magnitude.
The magnitude is given mathematically by:

$$|| a || = \sqrt{\sum_i a_i^2} $$

Where $a_i$ indicates the i'th coordinate of the vector.
Let's create a vector in numpy and check this definition:

In [7]:
import numpy as np

a = np.array([1.0, 3.0])

np.sqrt(np.sum(a**2))

3.1622776601683795

Or, more directly, we can directly compute the norm using
`np.linalg.norm`:

In [3]:
np.linalg.norm(a)

3.1622776601683795

The dot-product of two vectors is defined geometrically by:

$$ a \cdot b = || a || \times || b || \cdot cos(\theta) $$

Where $\theta$ is the angle between the vectors. This can be
directly computed in numpy as well:

In [8]:
b = np.array([2.0, 1.0])

np.dot(a, b)

5.0

The dot product is useful in part because it tells us how similar two
vectors are. If the product is zero, for example, the vectors are 
orthogonal to one another.

### Matricies and matrix product

A two dimensional numpy array can be thought of a matrix object. An $n$-by-$m$
matrix can be thought of as a particular type of mapping between two vector
spaces:

$$ \phi: \mathbb{R}^n \rightarrow \mathbb{R}^m $$

The set of all matricies describes all such mappings $\phi$ that are 
linear.

A common matrix operation is called the *matrix product*, given by:

$$ (A \cdot B)_{i, j} = \sum_{k = 1}^p a_{i, k} \cdot b_{k, j} $$

And defined whenever the number of columns in $A$ is the same as the number
of rows in $B$. Here, $a_{i, j}$ gives the value in the $i$'th row of and
$j$'th column of $A$. In the context of linear mappings, the matrix product
represents function composition.

To take a matrix product in Python, use the `@` symbol:

In [16]:
A = np.random.rand(3, 5)
B = np.random.rand(5, 2)

C = A @ B
print(C.shape)
C

(3, 2)


array([[1.34407763, 1.35334469],
       [1.53906827, 1.39081732],
       [0.6893045 , 0.58336984]])

Notice that the output has the same number of rows as $A$ and the same
number of columns as $B$.

### Solving linear systems

If we treat a vector as a matrix with a single column, we can write a system
of linear equations as a matrix product:

$$ A x = b $$

Where $A$ is a known matrix, $b$ is a known vector, and $x$ is the vector of
unknown quantities.

The function `np.linalg.solve` allows us to solve such a system efficently: 

In [22]:
A = np.random.rand(3, 3)
b = np.random.rand(3, 1)

x = np.linalg.solve(A, b)
x

array([[-0.93708537],
       [ 1.26108954],
       [-0.19803973]])

We can check that a reasonable solution as been found using matrix products:

In [24]:
err = A @ x - b
err

array([[5.55111512e-17],
       [5.55111512e-17],
       [5.55111512e-17]])

The solution is not exactly zero due to the numerical precision of the
machine, but the result is very small:

In [25]:
np.linalg.norm(err)

9.614813431917819e-17

-------

## Practice